export const GET_CRYPTOCURRENCY_START = 'GET_CRYPTOCURRENCY_START';
export const GET_CRYPTOCURRENCY_SUCCESS = 'GET_CRYPTOCURRENCY_SUCCESS';
export const GET_CRYPTOCURRENCY_FAIL = 'GET_CRYPTOCURRENCY_FAIL';